CREATE DATABASE sample;

USE sample;

CREATE TABLE customers (
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(255),
email VARCHAR(255),
PRIMARY KEY (id)
);


CHANGE MASTER TO MASTER_HOST='127.0.0.1', MASTER_PORT=3301, MASTER_USER='slave_user', MASTER_PASSWORD='password';
