CREATE DATABASE sample;

USE sample;

CREATE TABLE customers (
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(255),
email VARCHAR(255),
PRIMARY KEY (id)
);

UNLOCK TABLES;

GRANT REPLICATION SLAVE ON *.* TO 'slave_user'@'%' IDENTIFIED BY 'password';

FLUSH PRIVILEGES;
